alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: traction-dbs
  db_name: cc_tech
  db_user: cc_tech
  engine: MYSQL
  name: traction-dbs
  production: true
  version: "8"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: cc-tech
    match:
      path:
        prefix: /
name: cc-tech
region: nyc
services:
- build_command: npm run build
  environment_slug: php
  envs:
  - key: APP_NAME
    scope: RUN_AND_BUILD_TIME
    value: CC Manager
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:zNokXK2Tp4FC8naNvUg5xKd7DOW5+VXl:TteQp2vNOsLdNfFgcnXUsw34POMP3YUmD266ZvaePFk3gu96vCIUwIpJHJhH0x0E6yJB9RRJphuSvomaOfLbW7F5FA==]
  - key: APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${cc-tech.PUBLIC_URL}
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: debug
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${traction-dbs.DATABASE_URL}
  github:
    branch: production
    repo: clovercraft/cc-tech
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: cc-tech
  run_command: heroku-php-apache2 public/
  source_dir: /
