alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: traction-dbs
  db_name: cc_tech
  db_user: cc_tech
  engine: MYSQL
  name: traction-dbs
  production: true
  version: "8"
domains:
- domain: admin.clovercraft.gg
  type: PRIMARY
envs:
- key: LOG_CHANNEL
  scope: RUN_AND_BUILD_TIME
  value: logtail
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: cc-tech
    match:
      path:
        prefix: /
jobs:
- build_command: npm run build
  environment_slug: php
  envs:
  - key: DB_DATABASE
    scope: RUN_AND_BUILD_TIME
    value: cc_tech_test
  github:
    branch: production
    repo: clovercraft/cc-tech
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: POST_DEPLOY
  name: migrations
  run_command: php artisan migrate --force
  source_dir: /
name: clovercraft-tech
region: nyc
services:
- build_command: npm run build
  environment_slug: php
  envs:

  github:
    branch: production
    repo: clovercraft/cc-tech
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: cc-tech
  run_command: heroku-php-apache2 public/
  source_dir: /
workers:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: clovercraft/cctech-docker-cron
  instance_count: 1
  instance_size_slug: basic-xxs
  name: docker-cron
  source_dir: /
