name: Deploy Production

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy-app:
    name: Deploy to DO App
    runs-on: ubuntu-latest
    steps:
      - name: 'DigitalOcean App Platform deployment'
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: clovercraft-tech
          token: ${{ secrets.DO_TOKEN }}
