name: Deploy Production

on: workflow_dispatch

jobs:
  create-artifact:
    name: Create Version Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
      - name: 'Build FED'
        run: |
          npm install
          npm run build
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: 'Composer Install'
        run: composer install --no-dev --no-interaction --prefer-dist
      - name: 'Create Deployment Artifact'
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *
      - name: 'Store Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ${{github.sha}}.tar.gz
