name: Deploy Production

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: 'Composer Install'
        run: composer install --no-dev --no-interaction --prefer-dist
      - name: 'Run Test Suite'
        env:
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          DB_PORT: ${{ secrets.TEST_DB_PORT }}
          DB_DATABASE: ${{ secrets.TEST_DB_DATABASE }}
          DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        run: php artisan test

  deploy-app:
    name: Deploy to DO App
    runs-on: ubuntu-latest
    steps:
      - name: 'DigitalOcean App Platform deployment'
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: clovercraft-tech
          token: ${{ secrets.DO_TOKEN }}
