name: Laravel

on:
  push:
    branches: [ "production", "dev" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_DATABASE: testing
          MYSQL_USERNAME: sail
          MYSQL_PASSWORD: password
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: 'Checkout code'
      uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests
      run: php artisan test
      env:
          DB_HOST: mysql
